name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  setup-minikube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
          node-version: '20'

      - name: Install Minikube dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y conntrack

      - name: Install Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube

      - name: Start Minikube
        run: |
          minikube start --vm-driver=none

      # Descarga de la imagen del Docker Hub
      - name: Pull Docker image
        run: docker pull crcaceres05/devops_to_do_list:latest

      # Despliegue en Minikube
      - name: Deploy to Minikube - Deployment
        run: kubectl apply -f Kubernetes/deployment.yaml

      - name: Deploy to Minikube - Services
        run: kubectl apply -f Kubernetes/Service.yaml

      # Instalación de Prometheus y Grafana
      - name: Install Prometheus
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update
          helm install prometheus prometheus-community/prometheus

      - name: Install Grafana
        run: |
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo update
          helm install grafana grafana/grafana
